import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";

export const metadata: Metadata = {
  title: "Availabilityai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className="font-serif">
      <body
        className="font-serif antialiased bg-gray-900 text-gray-300"
      >
   
        <div className="flex">
  {/* Sidebar */}
  <Sidebar />

  {/* Main Content */}
  <div className="flex-1 bg-gray-900 text-gray-100 p-6">
    {children}
  </div>
</div>

      </body>
    </html>
  );
}
