import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Availabilityai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-gray-300`}
      >
        {/* Global Header */}
        <header className="bg-gray-800 p-4">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-lg font-semibold">AvailabilityAI</h1>
            <nav>
              <a href="/" className="px-4 hover:text-yellow-500">
                Home
              </a>
              <a href="/about" className="px-4 hover:text-yellow-500">
                About
              </a>
              <a href="/contact" className="px-4 hover:text-yellow-500">
                Contact
              </a>
            </nav>
          </div>
        </header>

        {/* Main Content */}
        <div className="flex min-h-screen">
          {/* Sidebar */}
         

          {/* Dynamic Page Content */}
          <main className="flex-1 p-6">{children}</main>
        </div>

        {/* Global Footer */}
        <footer className="bg-gray-800 p-4 text-center">
          <p>© 2025 AvailabilityAI. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
